/**
 * invoiceController.js — Invoice Logic
 *
 * One client can have MANY invoices (one-to-many).
 * This supports multiple sessions, split billing, re-invoicing, deposits, etc.
 *
 * Access rules:
 *   Staff — can generate invoices only for their own clients
 *           can view invoices that belong to their own clients
 *   Admin — can view all invoices; can mark any invoice paid
 *
 * Invoice number:
 *   Generated by invoiceUtils.generateInvoiceNumber(), which finds the
 *   current maximum issued number and adds 1. This correctly handles
 *   deletions and gaps (unlike a simple count() approach).
 *
 * Amount:
 *   Passed in the request body as `amount`.
 *   If omitted, defaults to the client's session price (client.price).
 *   Must be a positive number.
 *
 * Invoice preview shape (returned by generateInvoice and getInvoiceById):
 *   {
 *     id, invoiceNumber, amount, paymentStatus, createdAt,
 *     client:    { id, clientName, phone, price, photoFormat, orderStatus },
 *     createdBy: { id, name, email, phone },
 *     studio:    { name, address }   ← from env vars for the invoice header
 *   }
 */

const prisma                    = require("../utils/prismaClient");
const { success, error }        = require("../utils/responseUtils");
const { generateInvoiceNumber } = require("../utils/invoiceUtils");

// ─── Shared select shape ──────────────────────────────────────────────────────
// Used in generateInvoice (create), getInvoiceById (findUnique), and
// markInvoicePaid (update) so every full-invoice response has the same shape.
//
// Note: client.createdById is included here for the ownership check.
// It is stripped before the response is sent — the frontend never sees it.
const FULL_INVOICE_SELECT = {
  id:            true,
  invoiceNumber: true,
  amount:        true,
  paymentStatus: true,
  createdAt:     true,
  client: {
    select: {
      id:          true,
      clientName:  true,
      phone:       true,
      price:       true,
      photoFormat: true,
      orderStatus: true,
      createdById: true, // ownership check only — stripped before response
    },
  },
  createdBy: {
    select: { id: true, name: true, email: true, phone: true },
  },
};

// ─── Helper: build the studio block from environment ─────────────────────────
// The studio name and address appear on every printed invoice.
// Set STUDIO_NAME and STUDIO_ADDRESS in .env so the studio owner can configure
// them without touching code.
const studioInfo = () => ({
  name:    process.env.STUDIO_NAME    || "PixelStudio",
  address: process.env.STUDIO_ADDRESS || "14 Admiralty Way, Lekki Phase 1, Lagos, Nigeria",
});

// ─── Helper: strip internal FK + attach studio block ─────────────────────────
// Removes client.createdById (internal FK) from the response object and adds
// the studio block so the frontend has everything needed to render the invoice.
const formatInvoiceResponse = (invoice) => {
  const { createdById: _omit, ...clientData } = invoice.client;
  return { ...invoice, client: clientData, studio: studioInfo() };
};

// ─── GET /api/invoices ────────────────────────────────────────────────────────
/**
 * List invoices.
 *   Admin → all invoices in the system
 *   Staff → only invoices for clients they created
 *
 * Returns a lighter shape than the full invoice preview (no studio block)
 * since this is a list view, not an individual invoice render.
 */
const getAllInvoices = async (req, res, next) => {
  try {
    // For staff, filter to invoices whose client was created by this user.
    // Prisma translates { client: { createdById: req.user.id } } into a JOIN
    // with a WHERE clause on the clients table — no raw SQL needed.
    const where = req.user.role === "staff"
      ? { client: { createdById: req.user.id } }
      : {};

    const invoices = await prisma.invoice.findMany({
      where,
      select: {
        id:            true,
        invoiceNumber: true,
        amount:        true,
        paymentStatus: true,
        createdAt:     true,
        client: {
          select: {
            id:          true,
            clientName:  true,
            phone:       true,
            orderStatus: true,
          },
        },
        createdBy: {
          select: { id: true, name: true },
        },
      },
      orderBy: { createdAt: "desc" }, // most recent invoice first
    });

    return success(res, "Invoices fetched", invoices);
  } catch (err) {
    next(err);
  }
};

// ─── GET /api/invoices/:id ────────────────────────────────────────────────────
/**
 * Get one invoice with full details for the invoice preview / print page.
 * Returns the studio block so the frontend can render the invoice header.
 *
 * Ownership: staff can only view invoices for clients they created.
 */
const getInvoiceById = async (req, res, next) => {
  try {
    const invoice = await prisma.invoice.findUnique({
      where:  { id: req.params.id },
      select: FULL_INVOICE_SELECT,
    });

    if (!invoice) return error(res, "Invoice not found", 404);

    // Ownership check: staff may only view invoices for their own clients.
    // We compare against client.createdById (the FK on the client row), not
    // against invoice.createdById (the staff who generated this specific invoice).
    // This is intentional: what matters is who owns the CLIENT, not who typed
    // up this particular invoice.
    if (req.user.role === "staff" && invoice.client.createdById !== req.user.id) {
      return error(
        res,
        "Access denied. This invoice belongs to another staff member's client.",
        403
      );
    }

    return success(res, "Invoice fetched", formatInvoiceResponse(invoice));
  } catch (err) {
    next(err);
  }
};

// ─── POST /api/invoices/:clientId ─────────────────────────────────────────────
/**
 * Generate a new invoice for a client.
 *
 * Body (JSON):
 *   amount  {number}  optional — if omitted, defaults to client.price
 *
 * Multiple invoices per client are allowed: additional sessions, deposits,
 * re-invoicing after price changes, split billing, etc.
 *
 * Returns the full invoice preview shape so the frontend can immediately
 * render/print the invoice without a second GET request.
 */
const generateInvoice = async (req, res, next) => {
  try {
    const { clientId } = req.params;
    const { amount }   = req.body;

    // ── Validate amount if provided ───────────────────────────────────────────
    // If not provided, we fall back to client.price further below.
    // We validate here (before the DB hit) so the user gets a clear message.
    if (amount !== undefined && amount !== null && amount !== "") {
      const parsed = parseFloat(amount);
      if (isNaN(parsed) || parsed <= 0) {
        return error(res, "amount must be a positive number", 400);
      }
    }

    // ── Validate client exists and check ownership ────────────────────────────
    const client = await prisma.client.findUnique({
      where:  { id: clientId },
      select: { id: true, price: true, createdById: true },
    });

    if (!client) return error(res, "Client not found", 404);

    if (req.user.role === "staff" && client.createdById !== req.user.id) {
      return error(
        res,
        "Access denied. This client belongs to a different staff member.",
        403
      );
    }

    // ── Resolve the invoice amount ────────────────────────────────────────────
    // If the caller supplies an amount, use it. Otherwise default to the
    // client's session price so staff do not need to retype it every time.
    const resolvedAmount = (amount !== undefined && amount !== null && amount !== "")
      ? parseFloat(amount)
      : parseFloat(client.price); // Prisma returns Decimal as string in some drivers

    // ── Generate a unique invoice number ─────────────────────────────────────
    const invoiceNumber = await generateInvoiceNumber(prisma);

    // ── Create the invoice and return it with full details ────────────────────
    // Using `select` on the create call returns the created record with all
    // relations in a single round-trip — no need for a separate findUnique.
    const invoice = await prisma.invoice.create({
      data: {
        invoiceNumber,
        amount:        resolvedAmount,
        paymentStatus: "PENDING",   // every new invoice starts unpaid
        clientId,
        createdById:   req.user.id, // the logged-in staff member
      },
      select: FULL_INVOICE_SELECT,
    });

    return success(
      res,
      `Invoice ${invoiceNumber} generated successfully`,
      formatInvoiceResponse(invoice),
      201
    );
  } catch (err) {
    next(err);
  }
};

// ─── PATCH /api/invoices/:id/mark-paid ───────────────────────────────────────
/**
 * Mark a specific invoice as PAID.
 * Returns the full updated invoice so the frontend can re-render without
 * a second GET request.
 *
 * Guards:
 *   - 404 if invoice not found
 *   - 403 if staff tries to mark another staff member's client's invoice
 *   - 409 if invoice is already PAID (idempotency guard)
 */
const markInvoicePaid = async (req, res, next) => {
  try {
    // Lightweight pre-check: just the fields needed for guards
    const existing = await prisma.invoice.findUnique({
      where:  { id: req.params.id },
      select: {
        paymentStatus: true,
        client:        { select: { createdById: true } },
      },
    });

    if (!existing) return error(res, "Invoice not found", 404);

    if (req.user.role === "staff" && existing.client.createdById !== req.user.id) {
      return error(
        res,
        "Access denied. This invoice belongs to another staff member's client.",
        403
      );
    }

    if (existing.paymentStatus === "PAID") {
      return error(res, "This invoice is already marked as PAID.", 409);
    }

    // ── Update and return full invoice for immediate frontend re-render ────────
    const updated = await prisma.invoice.update({
      where:  { id: req.params.id },
      data:   { paymentStatus: "PAID" },
      select: FULL_INVOICE_SELECT,
    });

    return success(res, "Invoice marked as paid", formatInvoiceResponse(updated));
  } catch (err) {
    next(err);
  }
};

module.exports = { getAllInvoices, getInvoiceById, generateInvoice, markInvoicePaid };
